# Generated by Django 2.2 on 2021-11-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_servers_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='DataBase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.DataBases'),
        ),
    ]
