# Generated by Django 2.2 on 2021-12-08 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_tables_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='databases',
            name='CreateDate',
            field=models.DateField(default=datetime.date.today, help_text='Create date'),
        ),
        migrations.AddField(
            model_name='databases',
            name='DataSizeMB',
            field=models.IntegerField(default=0, help_text='Data size storage'),
        ),
        migrations.AddField(
            model_name='databases',
            name='Description',
            field=models.CharField(help_text='Database description', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databases',
            name='FriendlyName',
            field=models.CharField(help_text='Friendly Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='databases',
            name='IndexSizeMB',
            field=models.IntegerField(default=0, help_text='Index size storage'),
        ),
        migrations.AddField(
            model_name='databases',
            name='RoutinesNum',
            field=models.IntegerField(default=0, help_text='Number of routines'),
        ),
        migrations.AddField(
            model_name='databases',
            name='TablesNum',
            field=models.IntegerField(default=0, help_text='Number of tables'),
        ),
        migrations.AddField(
            model_name='databases',
            name='ViewsNum',
            field=models.IntegerField(default=0, help_text='Number of views'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='Environment',
            field=models.SmallIntegerField(choices=[(1, 'Production'), (2, 'QA'), (3, 'Development')], default=1, help_text='Database Enviroment'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='Status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Inaccessible')], default=1, help_text='Server status'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='Type',
            field=models.SmallIntegerField(choices=[(1, 'MS SQLServer'), (2, 'MySQL/MariaDB'), (3, 'PostgreSQL')], default=1, help_text='Type of Server'),
        ),
    ]
