# Generated by Django 2.2 on 2022-01-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20211208_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='DataBase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TablesOf', to='catalog.DataBases'),
        ),
    ]
