# Generated by Django 2.2 on 2022-02-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220215_0947'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='databases',
            table='catalog_databases',
        ),
        migrations.AlterModelTable(
            name='servers',
            table='catalog_servers',
        ),
        migrations.AlterModelTable(
            name='tablecategory',
            table='catalog_tablecategory',
        ),
        migrations.AlterModelTable(
            name='tables',
            table='catalog_tables',
        ),
    ]
