# Generated by Django 2.2 on 2022-11-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20220218_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(help_text='User name', max_length=30, verbose_name='User')),
                ('Pass', models.CharField(help_text='Password', max_length=30, verbose_name='Password')),
                ('Server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='his_credentials', to='catalog.Servers')),
            ],
            options={
                'verbose_name_plural': 'Credentials',
                'db_table': 'catalog_secures',
            },
        ),
    ]
