# Generated by Django 2.2 on 2023-01-24 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='Type',
            field=models.SmallIntegerField(choices=[(1, 'MS SQLServer'), (2, 'MySQL/MariaDB'), (3, 'PostgreSQL'), (4, 'MongoDB')], default=1, help_text='Type of Server'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='TableCategory',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.TableCategory'),
        ),
    ]
