# Generated by Django 2.2 on 2022-02-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='OfficeName',
            field=models.CharField(help_text='Office name', max_length=100, verbose_name='Office'),
        ),
    ]
