# Generated by Django 2.2 on 2022-02-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220203_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='CompanyEmail',
            field=models.EmailField(max_length=200, verbose_name='Office Email'),
        ),
    ]
