# Generated by Django 2.2 on 2022-02-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20220203_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='DisplayName',
            field=models.CharField(blank=True, default='', help_text='Firstname', max_length=200, null=True),
        ),
    ]
