# Generated by Django 2.2 on 2022-02-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20220203_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='CURP',
            field=models.CharField(blank=True, default='', help_text='CURP', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='employ',
            name='RFC',
            field=models.CharField(blank=True, default='', help_text='RFC', max_length=13, null=True),
        ),
    ]
