# Generated by Django 2.2 on 2022-02-18 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20220203_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='BirthDate',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
