# Generated by Django 2.2 on 2022-02-02 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(help_text='Category', max_length=30, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(help_text='Item Status', max_length=10, verbose_name='Item status')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationName', models.CharField(help_text='Location name', max_length=30, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=100)),
                ('InternalID', models.CharField(blank=True, help_text='Internal Id', max_length=100)),
                ('Brand', models.CharField(blank=True, help_text='Item Brand', max_length=30)),
                ('Model', models.CharField(blank=True, help_text='Item Model', max_length=30)),
                ('SerialNumber', models.CharField(blank=True, help_text='SN', max_length=100)),
                ('SKU', models.CharField(blank=True, help_text='SKU', max_length=100)),
                ('Color', models.CharField(blank=True, help_text='Item color', max_length=30)),
                ('Dimensions', models.CharField(blank=True, help_text='Item Size', max_length=30)),
                ('AssignedTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ItemCategory')),
                ('Status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ItemStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(help_text='Issue Description', max_length=20)),
                ('Date', models.DateField(help_text='Issue Date')),
                ('Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.IssuesType')),
            ],
        ),
    ]
