# Generated by Django 2.2 on 2022-02-03 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_itemcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ItemCondition'),
        ),
    ]
