# Generated by Django 2.2 on 2022-02-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Description',
            field=models.CharField(max_length=200),
        ),
    ]
