# Generated by Django 2.2 on 2022-02-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20220203_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Brand',
            field=models.CharField(blank=True, help_text='Item Brand', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Color',
            field=models.CharField(blank=True, help_text='Item color', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Dimensions',
            field=models.CharField(blank=True, help_text='Item Size', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Model',
            field=models.CharField(blank=True, help_text='Item Model', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='SKU',
            field=models.CharField(blank=True, help_text='SKU', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='SerialNumber',
            field=models.CharField(blank=True, help_text='SN', max_length=100, null=True),
        ),
    ]
