# Generated by Django 2.2 on 2022-02-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20220203_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='InternalID',
            field=models.CharField(blank=True, help_text='Internal Id', max_length=100, null=True),
        ),
    ]
