# Generated by Django 2.2 on 2022-02-03 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20220203_1417'),
        ('inventory', '0006_auto_20220203_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='AssignedTo',
        ),
        migrations.AddField(
            model_name='item',
            name='Employ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Employ'),
        ),
    ]
