# Generated by Django 2.2 on 2022-02-02 19:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Office',
            new_name='CompanyOffices',
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
