# Generated by Django 2.2 on 2022-02-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220202_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Office',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='User',
        ),
        migrations.DeleteModel(
            name='CompanyOffices',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
