# Generated by Django 2.2 on 2021-12-09 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_auto_20211208_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentDate', models.DateField(help_text='Update date info')),
                ('DataSizeMB', models.DecimalField(decimal_places=2, help_text='Data size storage', max_digits=12)),
                ('IndexSizeMB', models.DecimalField(decimal_places=2, help_text='Index size storage', max_digits=12)),
                ('RowsNum', models.IntegerField(help_text='Number of Rows allocated')),
                ('FKeysNum', models.IntegerField(help_text='Number of ForeingKeys')),
                ('IndexNum', models.IntegerField(help_text='Number of Indexes')),
                ('IndexReads', models.IntegerField(help_text='Index Reads')),
                ('IndexUpdates', models.IntegerField(help_text='Index updates')),
                ('Table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Tables')),
            ],
        ),
    ]
