# Generated by Django 2.2 on 2021-12-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20211208_1351'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableDetail',
            new_name='TablesDetail',
        ),
    ]
