# Generated by Django 2.2 on 2021-12-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20211209_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesdetail',
            name='LastAccess',
            field=models.DateField(help_text='Lastest table use date', null=True),
        ),
    ]
