# Generated by Django 2.2 on 2021-12-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20211208_1351'),
        ('tracking', '0003_tablesdetail_lastaccess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TablesDetail',
            new_name='TablesDetail_err',
        ),
    ]
