# Generated by Django 2.2 on 2021-12-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20211208_1351'),
        ('tracking', '0004_auto_20211209_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablesDetail',
            fields=[
                ('Table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.Tables')),
                ('CurrentDate', models.DateField(help_text='Update date info')),
                ('LastAccess', models.DateField(help_text='Lastest table use date', null=True)),
                ('DataSizeMB', models.DecimalField(decimal_places=2, help_text='Data size storage', max_digits=12)),
                ('IndexSizeMB', models.DecimalField(decimal_places=2, help_text='Index size storage', max_digits=12)),
                ('RowsNum', models.IntegerField(help_text='Number of Rows allocated')),
                ('FKeysNum', models.IntegerField(help_text='Number of ForeingKeys')),
                ('IndexNum', models.IntegerField(help_text='Number of Indexes')),
                ('IndexReads', models.IntegerField(help_text='Index Reads')),
                ('IndexUpdates', models.IntegerField(help_text='Index updates')),
            ],
        ),
    ]
