# Generated by Django 2.2 on 2021-12-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_tablesdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesdetail',
            name='Table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='DetailOf', serialize=False, to='catalog.Tables'),
        ),
    ]
