# Generated by Django 2.2 on 2021-12-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20211210_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TablesDetail_err',
        ),
    ]
