# Generated by Django 2.2 on 2021-12-21 06:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_auto_20211208_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.CharField(help_text='Job Name', max_length=50)),
                ('TargetDB', models.CharField(help_text='Destination Database', max_length=50)),
                ('Created', models.DateField(default=datetime.date.today)),
                ('SourceDB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.DataBases')),
            ],
        ),
        migrations.CreateModel(
            name='TableFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Column', models.CharField(help_text='Column Name', max_length=50)),
                ('FilterType', models.SmallIntegerField(choices=[(1, 'Equal to'), (2, 'Between'), (3, 'Iterate Between')], default=1, help_text='Filter by')),
                ('LowerValue', models.CharField(help_text='Lower limit', max_length=10)),
                ('UpperValue', models.CharField(help_text='Upper limit', max_length=10)),
                ('ValuesDataType', models.SmallIntegerField(choices=[(1, 'Numeric'), (2, 'String'), (3, 'Date')], default=1, help_text='Data type')),
                ('StepBy', models.SmallIntegerField(help_text='Iterate over')),
                ('Job', models.ManyToManyField(to='deploy.Jobs')),
                ('Table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Tables')),
            ],
        ),
        migrations.CreateModel(
            name='JobScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.SmallIntegerField(choices=[(1, 'DDL'), (2, 'DML'), (3, 'Other')], help_text='Type of script')),
                ('Order', models.IntegerField(help_text='Order of exec')),
                ('Job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.Jobs')),
            ],
        ),
    ]
