# Generated by Django 2.2 on 2021-12-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobscripts',
            name='Script',
            field=models.TextField(help_text='Sentence SQL to execute', null=True),
        ),
        migrations.AlterField(
            model_name='tablefilters',
            name='FilterType',
            field=models.SmallIntegerField(choices=[(0, 'Dont Filter'), (1, 'Equal to'), (2, 'Between'), (3, 'Iterate Between')], default=1, help_text='Filter by'),
        ),
        migrations.AlterField(
            model_name='tablefilters',
            name='ValuesDataType',
            field=models.SmallIntegerField(choices=[(1, 'Numeric'), (2, 'String'), (3, 'Date')], default=0, help_text='Data type'),
        ),
    ]
