# Generated by Django 2.2 on 2022-01-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20220110_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobscripts',
            name='Phase',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Building Objects'), (2, 'Transfer Data'), (3, 'Relational Objects'), (4, 'Ending database')], default=1, help_text='Phase of execution', null=True),
        ),
    ]
