# Generated by Django 2.2 on 2022-02-08 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_jobscripts_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='SourceDB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SourceFor', to='catalog.DataBases'),
        ),
    ]
