# Generated by Django 2.2 on 2022-11-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobName', models.CharField(help_text='Backup Job name', max_length=50)),
                ('IsLocal', models.BooleanField(default=False, help_text='add to local backup tool ', verbose_name='Run on local backup service.')),
                ('UseByPassDir', models.BooleanField(default=False, help_text='Use a bypass Dir? ', verbose_name='Use temporaly Dir')),
                ('ByPassDir', models.CharField(blank=True, help_text='Generate backup and move it later to Destination Dir', max_length=200, null=True, verbose_name='Temporaly Dir')),
                ('Database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.DataBases')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'db_table': 'backup_jobs',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationName', models.CharField(help_text='Location name', max_length=50, verbose_name='Location')),
                ('Host', models.CharField(help_text='Name or IP of host', max_length=30, null=True)),
                ('AbsolutePath', models.CharField(help_text='Absolute(local) path to backup file', max_length=200, null=True)),
                ('RemotePath', models.CharField(blank=True, help_text='Destination Remote path', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'db_table': 'backup_locations',
            },
        ),
        migrations.CreateModel(
            name='RotationJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobName', models.CharField(help_text='Rotation Job name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(help_text='Status', max_length=20, verbose_name='Status')),
                ('Description', models.CharField(blank=True, help_text='Status description', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Status',
                'db_table': 'backup_status',
            },
        ),
        migrations.CreateModel(
            name='RotationRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.SmallIntegerField(help_text='No.Rule')),
                ('RuleName', models.CharField(help_text='Rule rotation name', max_length=40)),
                ('Status', models.SmallIntegerField(choices=[(1, 'Enable'), (2, 'Disable')], default=1)),
                ('RetentionDays', models.SmallIntegerField(help_text='Total age of backup file', verbose_name='Expire at')),
                ('FileTag', models.CharField(blank=True, help_text='Add tag to filename ultil remains on this location', max_length=40, null=True)),
                ('ZipFile', models.BooleanField(default=False, help_text='Compress backup file on arrival ', verbose_name='Compress file?')),
                ('ZipFormat', models.SmallIntegerField(choices=[(1, '.zip'), (2, '.7z'), (3, '.tar')], default=1)),
                ('Job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.Jobs')),
                ('Location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.Locations')),
            ],
        ),
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedule', models.SmallIntegerField(choices=[(1, 'Daily'), (2, 'Weekend')], default=1)),
                ('Job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.Jobs')),
            ],
            options={
                'verbose_name_plural': 'Schedule',
                'db_table': 'backup_schedules',
            },
        ),
        migrations.AddField(
            model_name='jobs',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.Locations'),
        ),
        migrations.CreateModel(
            name='Backups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreationDate', models.DateField(blank=True, help_text='Create date', null=True)),
                ('StartBackup', models.DateTimeField(blank=True, help_text='Backup start time', null=True)),
                ('EndBackup', models.DateTimeField(blank=True, help_text='Backup end time', null=True)),
                ('FileName', models.CharField(help_text='File name', max_length=100)),
                ('SizeMB', models.DecimalField(decimal_places=2, default=0, help_text='Size MB', max_digits=20, null=True)),
                ('Size', models.BigIntegerField(default=0, help_text='Size', null=True)),
                ('Comments', models.TextField(blank=True, help_text='Comments', null=True)),
                ('Updated', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('Database', models.ForeignKey(help_text='Database', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.DataBases')),
                ('Job', models.ForeignKey(help_text='Job', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.Jobs')),
                ('Location', models.ForeignKey(help_text='Location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.Locations')),
                ('Status', models.ForeignKey(help_text='Status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.Status')),
            ],
            options={
                'verbose_name_plural': 'Backups',
                'db_table': 'backup_files',
            },
        ),
    ]
