# Generated by Django 2.2 on 2022-02-08 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20220111_1046'),
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobName', models.CharField(help_text='Rotation Job name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='Database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.DataBases'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='IsLocal',
            field=models.BooleanField(default=False, help_text='Is a local drive backup? ', verbose_name='Local backup'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.Locations'),
        ),
        migrations.AddField(
            model_name='locations',
            name='RemotePath',
            field=models.CharField(blank=True, help_text='Remote path', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='FilesPath',
            field=models.CharField(help_text='Absolute path', max_length=200),
        ),
        migrations.AlterField(
            model_name='status',
            name='Description',
            field=models.CharField(blank=True, help_text='Status description', max_length=200, null=True),
        ),
    ]
