# Generated by Django 2.2 on 2022-11-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='UseRemotePath',
            field=models.BooleanField(default=True, help_text='Saves on a network destination', verbose_name='Use the remote path location.'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='IsLocal',
            field=models.BooleanField(default=False, help_text='A DB Engine task run the backup', verbose_name='Run on self DB server.'),
        ),
    ]
