# Generated by Django 2.2 on 2022-02-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_auto_20220209_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backups',
            name='Size',
            field=models.BigIntegerField(default=0, help_text='Size', null=True),
        ),
        migrations.AlterField(
            model_name='backups',
            name='SizeMB',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Size MB', max_digits=20, null=True),
        ),
    ]
