# Generated by Django 2.2 on 2022-02-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0005_auto_20220209_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backups',
            options={'verbose_name_plural': 'Backups'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AddField(
            model_name='locations',
            name='Host',
            field=models.CharField(help_text='Name or IP of host', max_length=30, null=True),
        ),
    ]
