# Generated by Django 2.2 on 2022-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0006_auto_20220214_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='FilesPath',
        ),
        migrations.AddField(
            model_name='jobs',
            name='ByPassDir',
            field=models.CharField(help_text='Generate backup and move it later to Destination Dir', max_length=200, null=True, verbose_name='Temporaly Dir'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='UseByPassDir',
            field=models.BooleanField(default=False, help_text='Use the temporary Dir for generate backup? ', null=True, verbose_name='Local backup'),
        ),
        migrations.AddField(
            model_name='locations',
            name='AbsolutePath',
            field=models.CharField(help_text='Absolute(local) path to backup file', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='RemotePath',
            field=models.CharField(blank=True, help_text='Destination Remote path', max_length=200, null=True),
        ),
    ]
