# Generated by Django 2.2 on 2022-02-15 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0007_auto_20220215_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.SmallIntegerField(help_text='No.Rule')),
                ('RuleName', models.CharField(help_text='Rule rotation name', max_length=40)),
                ('Status', models.SmallIntegerField(choices=[(1, 'Enable'), (2, 'Disable')], default=1)),
                ('RetentionDays', models.SmallIntegerField(help_text='Days for Keep on this location')),
                ('FileTag', models.CharField(help_text='Add tag to filename ultil remains on this location', max_length=40)),
                ('ZipFile', models.BooleanField(default=False, help_text='Compress backup file on arrival ', verbose_name='Compress file?')),
                ('ZipFormat', models.SmallIntegerField(choices=[(1, 'zip'), (2, '7z'), (3, 'tar')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='jobs',
            name='ByPassDir',
            field=models.CharField(blank=True, help_text='Generate backup and move it later to Destination Dir', max_length=200, null=True, verbose_name='Temporaly Dir'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='UseByPassDir',
            field=models.BooleanField(default=False, help_text='Use a bypass Dir? ', verbose_name='Use temporaly Dir'),
        ),
        migrations.DeleteModel(
            name='Rotation',
        ),
        migrations.AddField(
            model_name='rotationrules',
            name='Job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.Jobs'),
        ),
        migrations.AddField(
            model_name='rotationrules',
            name='Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.Locations'),
        ),
    ]
