# Generated by Django 2.2 on 2022-02-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0008_auto_20220215_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotationrules',
            options={'verbose_name_plural': 'Rotation rules'},
        ),
        migrations.AlterField(
            model_name='rotationrules',
            name='FileTag',
            field=models.CharField(help_text='Add tag to filename ultil remains on this location', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='rotationrules',
            name='ZipFormat',
            field=models.SmallIntegerField(choices=[(1, '.zip'), (2, '.7z'), (3, '.tar')], default=1),
        ),
    ]
